<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, useTemplateRef, watch } from 'vue'
import ContextMenu, { type ContextMenuMethods } from 'primevue/contextmenu'
import ResizeKnob from '@/components/ResizeKnob.vue'
import SQLTableCellEditor from '@/components/table/SQLTableCellEditor.vue'
import { useToast } from 'primevue/usetoast'
import type { SQLTableColumn, SQLTableRowDraft } from '@/types/sql'

type CellPosition = {
  row: number
  column: number
}

const CELL_PREVIEW_TEXT_LIMIT = 150
const DRAG_SCROLL_THRESHOLD = 48
const DRAG_SCROLL_STEP = 20
const DEFAULT_ROW_HEIGHT = 34
const VIRTUAL_ROW_OVERSCAN = 12

const props = withDefaults(
  defineProps<{
    canEdit?: boolean
  }>(),
  {
    canEdit: true,
  },
)

const emit = defineEmits<{
  'update:focusedRowIndex': [value: number | null]
}>()

const columns = defineModel<SQLTableColumn[]>('columns', { required: true })
const rows = defineModel<SQLTableRowDraft[]>('rows', { required: true })

const toast = useToast()
const gridContainer = useTemplateRef<HTMLDivElement>('gridContainer')
const tableHead = useTemplateRef<HTMLTableSectionElement>('tableHead')
const editingEditor = useTemplateRef<InstanceType<typeof SQLTableCellEditor>>('editingEditor')
const contextMenu = useTemplateRef<ContextMenuMethods>('contextMenu')

const widths = ref<Record<string, number>>({})

const anchorCell = ref<CellPosition | null>(null)
const focusCell = ref<CellPosition | null>(null)
const editingCell = ref<CellPosition | null>(null)
const editingValue = ref<unknown>('')
const isDragging = ref(false)
const contextCell = ref<CellPosition | null>(null)
const dragPointer = ref<{ x: number; y: number } | null>(null)
const scrollTop = ref(0)
const viewportHeight = ref(0)
const headerHeight = ref(0)
const rowHeight = ref(DEFAULT_ROW_HEIGHT)

let dragScrollFrame = 0
let dragSelectionFrame = 0
let resizeObserver: ResizeObserver | null = null

const cellDisplayCache = new Map<
  string,
  {
    value: unknown
    segments: string[]
  }
>()

const createRowId = () =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `row-${Date.now()}-${Math.random().toString(36).slice(2)}`

const cloneCellValue = (value: unknown) => {
  if (value instanceof Date) {
    return new Date(value)
  }

  return value
}

const isGeneratedDefaultValue = (value: unknown) => {
  if (typeof value !== 'string') {
    return false
  }

  const normalized = value.trim().toLowerCase()
  return [
    'current_timestamp',
    'current_timestamp()',
    'current_date',
    'current_date()',
    'current_time',
    'current_time()',
    'localtimestamp',
    'localtimestamp()',
    'now()',
    'uuid()',
    'gen_random_uuid()',
  ].includes(normalized)
}

const isAutoGeneratedColumn = (column: SQLTableColumn) =>
  column.autoIncrement === true || isGeneratedDefaultValue(column.defaultValue)

const clampCell = (cell: CellPosition): CellPosition => ({
  row: Math.min(Math.max(cell.row, 0), Math.max(rows.value.length - 1, 0)),
  column: Math.min(Math.max(cell.column, 0), Math.max(columns.value.length - 1, 0)),
})

const isEditableColumn = (columnIndex: number) => {
  const column = columns.value[columnIndex]
  return props.canEdit && !!column && column.readOnly !== true
}

const findFirstEditableColumnIndex = () =>
  columns.value.findIndex((column) => column.readOnly !== true)

watch(
  columns,
  (nextColumns) => {
    widths.value = nextColumns.reduce(
      (previous, column) => ({
        ...previous,
        [column.field]: widths.value[column.field] ?? 220,
      }),
      {} as Record<string, number>,
    )
  },
  { immediate: true },
)

watch(rows, () => {
  cellDisplayCache.clear()
  scheduleGridMeasurement()
})

watch(columns, () => {
  cellDisplayCache.clear()
  scheduleGridMeasurement()
})

const hasRows = computed(() => rows.value.length > 0 && columns.value.length > 0)
const visibleRowCount = computed(() => {
  if (!hasRows.value) {
    return 0
  }

  const availableHeight = Math.max(viewportHeight.value - headerHeight.value, rowHeight.value)
  return Math.ceil(availableHeight / rowHeight.value) + VIRTUAL_ROW_OVERSCAN * 2
})
const visibleRowStart = computed(() => {
  if (!hasRows.value) {
    return 0
  }

  return Math.max(
    0,
    Math.floor(Math.max(scrollTop.value - headerHeight.value, 0) / rowHeight.value) -
      VIRTUAL_ROW_OVERSCAN,
  )
})
const visibleRowEnd = computed(() =>
  Math.min(rows.value.length, visibleRowStart.value + visibleRowCount.value),
)
const visibleRows = computed(() =>
  rows.value
    .slice(visibleRowStart.value, visibleRowEnd.value)
    .map((row, index) => ({ row, rowIndex: visibleRowStart.value + index })),
)
const virtualPaddingTop = computed(() => visibleRowStart.value * rowHeight.value)
const virtualPaddingBottom = computed(() =>
  Math.max(0, (rows.value.length - visibleRowEnd.value) * rowHeight.value),
)
const rowHeaderColumnWidth = computed(() => {
  const rowDigits = Math.max(3, String(Math.max(rows.value.length, 1)).length)
  return Math.max(56, 48 + rowDigits * 8)
})
const focusedRowIndex = computed(() => {
  if (focusCell.value === null) {
    return null
  }

  return focusCell.value.row < rows.value.length ? focusCell.value.row : null
})

const selectionRange = computed(() => {
  if (!anchorCell.value || !focusCell.value || !hasRows.value) return null

  return {
    startRow: Math.min(anchorCell.value.row, focusCell.value.row),
    endRow: Math.max(anchorCell.value.row, focusCell.value.row),
    startColumn: Math.min(anchorCell.value.column, focusCell.value.column),
    endColumn: Math.max(anchorCell.value.column, focusCell.value.column),
  }
})

const selectedRowIndexes = computed(() => {
  if (!selectionRange.value) return []
  return Array.from(
    { length: selectionRange.value.endRow - selectionRange.value.startRow + 1 },
    (_, index) => selectionRange.value!.startRow + index,
  )
})

const selectedColumnIndexes = computed(() => {
  if (!selectionRange.value) return []
  return Array.from(
    { length: selectionRange.value.endColumn - selectionRange.value.startColumn + 1 },
    (_, index) => selectionRange.value!.startColumn + index,
  )
})

const selectionIsSingleCell = computed(
  () =>
    !!selectionRange.value &&
    selectionRange.value.startRow === selectionRange.value.endRow &&
    selectionRange.value.startColumn === selectionRange.value.endColumn,
)
const selectionOverlayStyle = computed(() => {
  if (!selectionRange.value || !columns.value.length) {
    return null
  }

  const startColumn = Math.max(0, Math.min(selectionRange.value.startColumn, columns.value.length - 1))
  const endColumn = Math.max(0, Math.min(selectionRange.value.endColumn, columns.value.length - 1))

  let width = 0
  for (let columnIndex = startColumn; columnIndex <= endColumn; columnIndex += 1) {
    width += widths.value[columns.value[columnIndex]!.field] ?? 220
  }

  let left = rowHeaderColumnWidth.value
  for (let columnIndex = 0; columnIndex < startColumn; columnIndex += 1) {
    left += widths.value[columns.value[columnIndex]!.field] ?? 220
  }

  return {
    top: `${headerHeight.value + selectionRange.value.startRow * rowHeight.value}px`,
    left: `${left}px`,
    width: `${Math.max(width, 1)}px`,
    height: `${Math.max(
      (selectionRange.value.endRow - selectionRange.value.startRow + 1) * rowHeight.value,
      rowHeight.value,
    )}px`,
  }
})

const focusGrid = () => {
  gridContainer.value?.focus()
}

const measureGridMetrics = () => {
  viewportHeight.value = gridContainer.value?.clientHeight ?? viewportHeight.value

  const nextHeaderHeight = tableHead.value?.getBoundingClientRect().height
  if (nextHeaderHeight && Number.isFinite(nextHeaderHeight)) {
    headerHeight.value = nextHeaderHeight
  }

  const nextRowHeight = gridContainer.value
    ?.querySelector<HTMLTableRowElement>('tr[data-row-index]')
    ?.getBoundingClientRect().height
  if (nextRowHeight && Number.isFinite(nextRowHeight)) {
    rowHeight.value = nextRowHeight
  }
}

const scheduleGridMeasurement = () => {
  nextTick(() => {
    requestAnimationFrame(() => {
      measureGridMetrics()
    })
  })
}

const getCellElement = (cell: CellPosition) =>
  gridContainer.value?.querySelector<HTMLTableCellElement>(
    `td[data-cell-row="${cell.row}"][data-cell-column="${cell.column}"]`,
  ) ?? null

const scrollRenderedCellIntoView = (
  container: HTMLDivElement,
  targetCell: HTMLTableCellElement,
) => {
  const containerRect = container.getBoundingClientRect()
  const cellRect = targetCell.getBoundingClientRect()
  const viewportLeft = containerRect.left + rowHeaderColumnWidth.value
  const viewportTop = containerRect.top + headerHeight.value

  if (cellRect.left < viewportLeft) {
    container.scrollLeft = Math.max(0, container.scrollLeft - (viewportLeft - cellRect.left))
  } else if (cellRect.right > containerRect.right) {
    container.scrollLeft += cellRect.right - containerRect.right
  }

  if (cellRect.top < viewportTop) {
    container.scrollTop = Math.max(0, container.scrollTop - (viewportTop - cellRect.top))
  } else if (cellRect.bottom > containerRect.bottom) {
    container.scrollTop += cellRect.bottom - containerRect.bottom
  }

  scrollTop.value = container.scrollTop
}

const ensureCellVisible = (cell: CellPosition) => {
  nextTick(() => {
    const container = gridContainer.value
    if (!container) {
      return
    }

    const targetCell = getCellElement(cell)
    if (targetCell) {
      scrollRenderedCellIntoView(container, targetCell)
      return
    }

    const targetTop = headerHeight.value + cell.row * rowHeight.value
    const targetBottom = targetTop + rowHeight.value
    const viewportTop = container.scrollTop + headerHeight.value
    const viewportBottom = container.scrollTop + container.clientHeight

    if (targetTop < viewportTop) {
      container.scrollTop = Math.max(0, targetTop - headerHeight.value)
      scrollTop.value = container.scrollTop
    } else if (targetBottom > viewportBottom) {
      container.scrollTop = Math.max(0, targetBottom - container.clientHeight)
      scrollTop.value = container.scrollTop
    }

    requestAnimationFrame(() => {
      const nextTargetCell = getCellElement(cell)
      if (nextTargetCell) {
        scrollRenderedCellIntoView(container, nextTargetCell)
      }
    })
  })
}

const restoreGridFocusAfterEdit = () => {
  nextTick(() => {
    requestAnimationFrame(() => {
      focusGrid()
    })
  })
}

const finishPendingEdit = (nextCell?: CellPosition) => {
  if (!editingCell.value) return

  if (
    nextCell &&
    editingCell.value.row === nextCell.row &&
    editingCell.value.column === nextCell.column
  ) {
    return
  }

  commitEditing()
}

const setSelection = (
  cell: CellPosition,
  options?: { extend?: boolean; ensureVisible?: boolean },
) => {
  if (!hasRows.value) return

  const nextCell = clampCell(cell)
  finishPendingEdit(nextCell)

  if (options?.extend && anchorCell.value) {
    focusCell.value = nextCell
  } else {
    anchorCell.value = nextCell
    focusCell.value = nextCell
  }

  focusGrid()

  if (options?.ensureVisible !== false) {
    ensureCellVisible(nextCell)
  }
}

const selectAll = () => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: 0, column: 0 }
  focusCell.value = { row: rows.value.length - 1, column: columns.value.length - 1 }
  editingCell.value = null
  focusGrid()
}

const selectRow = (index: number) => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: index, column: 0 }
  focusCell.value = { row: index, column: columns.value.length - 1 }
  editingCell.value = null
  focusGrid()
}

const selectColumn = (index: number) => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: 0, column: index }
  focusCell.value = { row: rows.value.length - 1, column: index }
  editingCell.value = null
  focusGrid()
}

const isCellSelected = (rowIndex: number, columnIndex: number) => {
  if (!selectionRange.value) return false

  return (
    rowIndex >= selectionRange.value.startRow &&
    rowIndex <= selectionRange.value.endRow &&
    columnIndex >= selectionRange.value.startColumn &&
    columnIndex <= selectionRange.value.endColumn
  )
}

const isColumnSelected = (columnIndex: number) => selectedColumnIndexes.value.includes(columnIndex)

const valuesEqual = (left: unknown, right: unknown) => {
  if (left === right) return true

  if (left instanceof Date && right instanceof Date) {
    return left.getTime() === right.getTime()
  }

  return false
}

const recomputeRowState = (rowIndex: number) => {
  const row = rows.value[rowIndex]

  if (!row || row.state === 'deleted') return
  if (!row.original) {
    row.state = 'new'
    return
  }

  const isDirty = columns.value.some(
    (column) => !valuesEqual(row.values[column.field], row.original?.[column.field]),
  )

  row.state = isDirty ? 'modified' : 'clean'
}

const getValue = (rowIndex: number, columnIndex: number) => {
  const row = rows.value[rowIndex]
  const column = columns.value[columnIndex]
  return row?.values?.[column.field]
}

const getRowValue = (row: SQLTableRowDraft, column: SQLTableColumn) => row.values[column.field]

const formatDisplayValue = (value: unknown) => {
  const text =
    typeof value === 'string' ? value : value === null || value === undefined ? '' : String(value)

  if (text.length <= CELL_PREVIEW_TEXT_LIMIT) {
    return text
  }

  return `${text.slice(0, CELL_PREVIEW_TEXT_LIMIT)}…`
}

const getDisplaySegments = (value: unknown) => {
  const text = formatDisplayValue(value)

  return text.split(/(\r?\n)/).filter((segment) => segment.length > 0)
}

const getCachedDisplaySegments = (row: SQLTableRowDraft, column: SQLTableColumn) => {
  const key = `${row.id}:${column.field}`
  const value = getRowValue(row, column)
  const cached = cellDisplayCache.get(key)

  if (cached && cached.value === value) {
    return cached.segments
  }

  const segments = getDisplaySegments(value)
  cellDisplayCache.set(key, {
    value,
    segments,
  })
  return segments
}

const pad = (value: number) => String(value).padStart(2, '0')

const getEditorKind = (column: SQLTableColumn) => {
  const type = (column.type || '').toLowerCase()

  if (column.enumValues?.length) return 'enum'
  if (/\b(timestamp|datetime)\b/.test(type)) return 'datetime'
  if (/\btime\b/.test(type) && !/\b(timestamp|datetime)\b/.test(type)) return 'time'
  if (/\bdate\b/.test(type)) return 'date'

  return 'text'
}

const formatDateForColumn = (value: Date, kind: ReturnType<typeof getEditorKind>) => {
  if (kind === 'date') {
    return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`
  }

  if (kind === 'time') {
    return `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
  }

  return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())} ${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
}

const normalizeInputValue = (rawValue: unknown, rowIndex: number, columnIndex: number) => {
  const column = columns.value[columnIndex]
  const currentValue = getValue(rowIndex, columnIndex)
  const type = (column.type || '').toLowerCase()
  const editorKind = getEditorKind(column)

  if (rawValue instanceof Date) {
    return formatDateForColumn(rawValue, editorKind)
  }

  if (rawValue === null || rawValue === undefined) {
    return column.nullable !== false ? null : currentValue
  }

  const normalized = String(rawValue).trim()

  if (normalized === '' && column.nullable !== false) {
    return null
  }

  if (typeof currentValue === 'number' || /(int|decimal|float|double)/.test(type)) {
    const numericValue = Number(rawValue)
    return Number.isNaN(numericValue) ? rawValue : numericValue
  }

  if (typeof currentValue === 'boolean' || /(bool|tinyint\(1\))/.test(type)) {
    return ['1', 'true', 'yes'].includes(normalized.toLowerCase())
  }

  return rawValue
}

const setValue = (rowIndex: number, columnIndex: number, value: unknown) => {
  const row = rows.value[rowIndex]
  if (!row || row.state === 'deleted') return

  const field = columns.value[columnIndex].field
  row.values = {
    ...row.values,
    [field]: value,
  }

  recomputeRowState(rowIndex)
}

const startEditing = (rowIndex: number, columnIndex: number) => {
  if (!isEditableColumn(columnIndex)) return
  if (rows.value[rowIndex]?.state === 'deleted') return

  setSelection({ row: rowIndex, column: columnIndex })
  editingCell.value = { row: rowIndex, column: columnIndex }
  editingValue.value = getValue(rowIndex, columnIndex) ?? null

  nextTick(() => {
    editingEditor.value?.focusEditor()
  })
}

const commitEditing = () => {
  if (!editingCell.value) return

  const { row, column } = editingCell.value
  setValue(row, column, normalizeInputValue(editingValue.value, row, column))
  editingCell.value = null
}

const cancelEditing = () => {
  editingCell.value = null
  restoreGridFocusAfterEdit()
}

const addRow = () => {
  const values = columns.value.reduce(
    (previous, column) => ({
      ...previous,
      [column.field]: column.defaultValue ?? null,
    }),
    {},
  )

  rows.value.push({
    id: createRowId(),
    values,
    original: null,
    state: 'new',
  })

  const rowIndex = rows.value.length - 1
  const editableColumnIndex = findFirstEditableColumnIndex()
  const targetColumn = editableColumnIndex >= 0 ? editableColumnIndex : 0
  setSelection({ row: rowIndex, column: targetColumn })
  if (editableColumnIndex >= 0) {
    startEditing(rowIndex, editableColumnIndex)
  }
}

const duplicateSelectedRows = () => {
  if (!selectedRowIndexes.value.length) return
  finishPendingEdit()

  const insertionIndex = Math.max(...selectedRowIndexes.value) + 1
  const duplicates = selectedRowIndexes.value
    .map((rowIndex) => rows.value[rowIndex])
    .filter((row): row is SQLTableRowDraft => !!row && row.state !== 'deleted')
    .map((row) => ({
      id: createRowId(),
      values: columns.value.reduce(
        (previous, column) => ({
          ...previous,
          [column.field]: isAutoGeneratedColumn(column)
            ? null
            : cloneCellValue(row.values[column.field]),
        }),
        {} as Record<string, unknown>,
      ),
      original: null,
      state: 'new' as const,
    }))

  if (!duplicates.length) return

  rows.value.splice(insertionIndex, 0, ...duplicates)
  setSelection({
    row: insertionIndex,
    column: focusCell.value?.column ?? 0,
  })
}

const deleteSelectedRows = () => {
  if (!selectedRowIndexes.value.length) return
  finishPendingEdit()

  const indexes = [...selectedRowIndexes.value].sort((left, right) => right - left)

  for (const index of indexes) {
    const row = rows.value[index]
    if (!row) continue

    if (!row.original) {
      rows.value.splice(index, 1)
      continue
    }

    row.state = row.state === 'deleted' ? 'clean' : 'deleted'
  }

  editingCell.value = null

  if (rows.value.length) {
    setSelection({
      row: Math.min(indexes[indexes.length - 1], rows.value.length - 1),
      column: focusCell.value?.column ?? 0,
    })
  } else {
    anchorCell.value = null
    focusCell.value = null
  }
}

const setSelectionToNull = () => {
  if (!props.canEdit || !selectionRange.value) return

  for (let row = selectionRange.value.startRow; row <= selectionRange.value.endRow; row += 1) {
    if (rows.value[row]?.state === 'deleted') continue

    for (
      let column = selectionRange.value.startColumn;
      column <= selectionRange.value.endColumn;
      column += 1
    ) {
      if (!isEditableColumn(column)) continue
      setValue(row, column, null)
    }
  }
}

const discardSelectedChanges = () => {
  const indexes = [...selectedRowIndexes.value].sort((left, right) => right - left)

  for (const rowIndex of indexes) {
    const row = rows.value[rowIndex]
    if (!row || row.state === 'deleted') continue

    if (!row.original) {
      rows.value.splice(rowIndex, 1)
      continue
    }

    row.values = { ...row.original }
    row.state = 'clean'
  }
}

const formatCellValue = (value: unknown) => {
  if (value === null || value === undefined) return 'NULL'
  return String(value)
}

const copySelection = async () => {
  if (!selectionRange.value) return

  const lines = []

  for (let row = selectionRange.value.startRow; row <= selectionRange.value.endRow; row += 1) {
    const line = []

    for (
      let column = selectionRange.value.startColumn;
      column <= selectionRange.value.endColumn;
      column += 1
    ) {
      line.push(formatCellValue(getValue(row, column)))
    }

    lines.push(line.join('\t'))
  }

  try {
    await navigator.clipboard.writeText(lines.join('\n'))
    toast.add({
      severity: 'success',
      summary: 'Copied selection',
      detail: 'Selection copied as tab-separated text',
      life: 1500,
    })
  } catch {
    toast.add({
      severity: 'warn',
      summary: 'Clipboard unavailable',
      detail: 'The selection could not be copied automatically',
      life: 1800,
    })
  }
}

const moveSelection = (deltaRow: number, deltaColumn: number, extend: boolean) => {
  if (!hasRows.value) return

  const baseCell = (extend ? focusCell.value : anchorCell.value) ?? { row: 0, column: 0 }
  setSelection(
    {
      row: baseCell.row + deltaRow,
      column: baseCell.column + deltaColumn,
    },
    { extend, ensureVisible: true },
  )
}

const updateDragSelectionFromPointer = (clientX: number, clientY: number) => {
  if (!isDragging.value || !anchorCell.value || !gridContainer.value) {
    return
  }

  const containerRect = gridContainer.value.getBoundingClientRect()
  const probeX = Math.min(Math.max(clientX, containerRect.left + 2), containerRect.right - 2)
  const probeY = Math.min(Math.max(clientY, containerRect.top + 2), containerRect.bottom - 2)
  const element = document.elementFromPoint(probeX, probeY)
  const cell = element?.closest?.(
    'td[data-cell-row][data-cell-column]',
  ) as HTMLTableCellElement | null

  if (!cell) {
    return
  }

  const row = Number(cell.dataset.cellRow)
  const column = Number(cell.dataset.cellColumn)

  if (Number.isNaN(row) || Number.isNaN(column)) {
    return
  }

  focusCell.value = clampCell({ row, column })
}

const runDragSelection = () => {
  dragSelectionFrame = 0

  if (!isDragging.value || !dragPointer.value) {
    return
  }

  updateDragSelectionFromPointer(dragPointer.value.x, dragPointer.value.y)
}

const scheduleDragSelection = () => {
  if (dragSelectionFrame) {
    return
  }

  dragSelectionFrame = requestAnimationFrame(runDragSelection)
}

const stopDragSelection = () => {
  if (dragSelectionFrame) {
    cancelAnimationFrame(dragSelectionFrame)
    dragSelectionFrame = 0
  }
}

const stopDragAutoScroll = () => {
  if (dragScrollFrame) {
    cancelAnimationFrame(dragScrollFrame)
    dragScrollFrame = 0
  }
}

const runDragAutoScroll = () => {
  if (!isDragging.value || !dragPointer.value || !gridContainer.value) {
    dragScrollFrame = 0
    return
  }

  const container = gridContainer.value
  const rect = container.getBoundingClientRect()
  let deltaX = 0
  let deltaY = 0

  if (dragPointer.value.x < rect.left + DRAG_SCROLL_THRESHOLD) {
    deltaX = -Math.ceil(
      ((rect.left + DRAG_SCROLL_THRESHOLD - dragPointer.value.x) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  } else if (dragPointer.value.x > rect.right - DRAG_SCROLL_THRESHOLD) {
    deltaX = Math.ceil(
      ((dragPointer.value.x - (rect.right - DRAG_SCROLL_THRESHOLD)) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  }

  if (dragPointer.value.y < rect.top + DRAG_SCROLL_THRESHOLD) {
    deltaY = -Math.ceil(
      ((rect.top + DRAG_SCROLL_THRESHOLD - dragPointer.value.y) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  } else if (dragPointer.value.y > rect.bottom - DRAG_SCROLL_THRESHOLD) {
    deltaY = Math.ceil(
      ((dragPointer.value.y - (rect.bottom - DRAG_SCROLL_THRESHOLD)) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  }

  if (deltaX || deltaY) {
    container.scrollLeft += deltaX
    container.scrollTop += deltaY
    scrollTop.value = container.scrollTop
    updateDragSelectionFromPointer(dragPointer.value.x, dragPointer.value.y)
  }

  dragScrollFrame = requestAnimationFrame(runDragAutoScroll)
}

const startDragAutoScroll = () => {
  if (dragScrollFrame) {
    return
  }

  dragScrollFrame = requestAnimationFrame(runDragAutoScroll)
}

const onGridKeyDown = (event: KeyboardEvent) => {
  if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)
    return

  if (!hasRows.value) return

  const extend = event.shiftKey
  const commandOrCtrl = event.metaKey || event.ctrlKey

  if (commandOrCtrl && event.code === 'KeyA') {
    selectAll()
    event.preventDefault()
    return
  }

  if (commandOrCtrl && event.code === 'KeyC') {
    void copySelection()
    event.preventDefault()
    return
  }

  if (props.canEdit && commandOrCtrl && event.code === 'KeyD') {
    duplicateSelectedRows()
    event.preventDefault()
    return
  }

  if (event.code === 'Enter' || event.code === 'F2') {
    const cell = focusCell.value ?? { row: 0, column: 0 }
    startEditing(cell.row, cell.column)
    event.preventDefault()
    return
  }

  if (props.canEdit && commandOrCtrl && (event.code === 'Delete' || event.code === 'Backspace')) {
    deleteSelectedRows()
    event.preventDefault()
    return
  }

  if (props.canEdit && event.code === 'Delete') {
    setSelectionToNull()
    event.preventDefault()
    return
  }

  if (event.code === 'Tab') {
    moveSelection(0, event.shiftKey ? -1 : 1, false)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowRight') {
    moveSelection(0, 1, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowLeft') {
    moveSelection(0, -1, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowDown') {
    moveSelection(1, 0, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowUp') {
    moveSelection(-1, 0, extend)
    event.preventDefault()
  }
}

const onCellMouseDown = (event: MouseEvent, rowIndex: number, columnIndex: number) => {
  if (event.button !== 0) return

  event.preventDefault()
  isDragging.value = true
  dragPointer.value = { x: event.clientX, y: event.clientY }
  setSelection(
    { row: rowIndex, column: columnIndex },
    { extend: event.shiftKey, ensureVisible: true },
  )
  startDragAutoScroll()
}

const onDocumentMouseMove = (event: MouseEvent) => {
  if (!isDragging.value) {
    return
  }

  dragPointer.value = { x: event.clientX, y: event.clientY }
  scheduleDragSelection()
  startDragAutoScroll()
}

const onDocumentMouseUp = () => {
  isDragging.value = false
  dragPointer.value = null
  stopDragSelection()
  stopDragAutoScroll()
}

const onGridScroll = () => {
  scrollTop.value = gridContainer.value?.scrollTop ?? 0
}

const showContextMenu = (event: MouseEvent, rowIndex?: number, columnIndex?: number) => {
  finishPendingEdit(
    rowIndex !== undefined && columnIndex !== undefined
      ? { row: rowIndex, column: columnIndex }
      : undefined,
  )

  if (rowIndex !== undefined && columnIndex !== undefined) {
    contextCell.value = { row: rowIndex, column: columnIndex }
    if (!isCellSelected(rowIndex, columnIndex)) {
      setSelection({ row: rowIndex, column: columnIndex })
    }
  }

  contextMenu.value?.show(event)
}

const contextMenuItems = computed(() => [
  {
    label: 'Edit cell',
    icon: 'ti ti-edit',
    disabled:
      !selectionIsSingleCell.value ||
      !props.canEdit ||
      !focusCell.value ||
      !isEditableColumn(focusCell.value.column),
    command: () => {
      const cell = focusCell.value
      if (cell) startEditing(cell.row, cell.column)
    },
  },
  {
    label: 'Copy selection',
    icon: 'ti ti-copy',
    command: () => void copySelection(),
  },
  {
    label: 'Set NULL',
    icon: 'ti ti-eraser',
    disabled: !props.canEdit,
    command: setSelectionToNull,
  },
  { separator: true },
  {
    label: 'Insert row',
    icon: 'ti ti-row-insert-bottom',
    disabled: !props.canEdit,
    command: addRow,
  },
  {
    label: 'Duplicate row(s)',
    icon: 'ti ti-copy-plus',
    disabled: !props.canEdit,
    command: duplicateSelectedRows,
  },
  {
    label: 'Delete row(s)',
    icon: 'ti ti-trash',
    disabled: !props.canEdit,
    command: deleteSelectedRows,
  },
  {
    label: 'Discard row changes',
    icon: 'ti ti-restore',
    disabled: !props.canEdit,
    command: discardSelectedChanges,
  },
])

onMounted(() => {
  measureGridMetrics()
  resizeObserver = new ResizeObserver(() => {
    measureGridMetrics()
  })
  if (gridContainer.value) {
    resizeObserver.observe(gridContainer.value)
  }
  if (tableHead.value) {
    resizeObserver.observe(tableHead.value)
  }
  window.addEventListener('mousemove', onDocumentMouseMove)
  window.addEventListener('mouseup', onDocumentMouseUp)
})

onUnmounted(() => {
  resizeObserver?.disconnect()
  resizeObserver = null
  stopDragSelection()
  stopDragAutoScroll()
  window.removeEventListener('mousemove', onDocumentMouseMove)
  window.removeEventListener('mouseup', onDocumentMouseUp)
})

watch(
  focusedRowIndex,
  (nextValue) => {
    emit('update:focusedRowIndex', nextValue)
  },
  { immediate: true },
)

defineExpose({
  addRow,
  duplicateSelectedRows,
  deleteSelectedRows,
  focusGrid,
  focusRow: (rowIndex: number, columnIndex = 0) => {
    if (!rows.value[rowIndex]) {
      return
    }

    setSelection({ row: rowIndex, column: columnIndex })
  },
  getFocusedRowIndex: () => focusedRowIndex.value,
  getSelectedRowIndexes: () => [...selectedRowIndexes.value],
})
</script>

<template>
  <div
    ref="gridContainer"
    tabindex="0"
    class="relative h-full overflow-auto outline-none"
    @keydown="onGridKeyDown"
    @scroll="onGridScroll"
    @contextmenu.prevent="showContextMenu($event)"
  >
    <div class="relative w-fit min-w-full">
      <div
        v-if="selectionOverlayStyle"
        class="pointer-events-none absolute z-10 rounded-[3px] bg-primary-500/15 ring-inset ring-1 ring-primary-500/30"
        :style="selectionOverlayStyle"
      />

      <table class="m-[-1px] select-none" style="width: max-content">
      <thead ref="tableHead">
        <tr class="sticky top-0 left-0 bg-[#F9F9F9] dark:bg-[#202020] z-20">
          <th
            class="sticky left-0 z-30 bg-[#F9F9F9] dark:bg-[#202020] border app-border border-t-0 border-l-0"
            :style="{
              width: `${rowHeaderColumnWidth}px`,
              minWidth: `${rowHeaderColumnWidth}px`,
              maxWidth: `${rowHeaderColumnWidth}px`,
            }"
          >
            <button
              class="w-full h-full min-w-[3rem] hover:bg-neutral-500/10 text-xs uppercase tracking-[0.14em] rounded-md py-2 opacity-55"
              @click="selectAll"
            >
              All
            </button>
          </th>

          <th
            v-for="(column, columnIndex) of columns"
            :key="column.field"
            align="left"
            class="border app-border font-normal mono text-xs relative border-t-0 select-none"
            :class="{ 'bg-black/5 dark:bg-white/10': isColumnSelected(columnIndex) }"
            :style="{ width: `${widths[column.field] || 220}px` }"
            @click="selectColumn(columnIndex)"
          >
            <div class="flex items-center gap-2 justify-between px-2 py-1">
              <div class="flex items-center gap-2 min-w-0">
                <i
                  :class="`ti ${column.primaryKey ? 'ti-key text-amber-500' : 'ti-columns-3 opacity-50'}`"
                />
                <div class="flex flex-col min-w-0">
                  <span class="truncate">{{ column.name }}</span>
                  <span class="truncate text-[10px] opacity-45 mt-[-2px]">{{
                    column.type || 'column'
                  }}</span>
                </div>
              </div>
              <i class="ti ti-selector opacity-35" />
            </div>

            <ResizeKnob
              v-model:width="widths[column.field]"
              class="absolute right-[-0.3rem] top-0 z-10"
            />
          </th>
        </tr>
      </thead>

      <tbody>
        <tr v-if="virtualPaddingTop > 0" aria-hidden="true">
          <td
            :colspan="columns.length + 1"
            class="border-0 p-0"
            :style="{ height: `${virtualPaddingTop}px` }"
          />
        </tr>

        <tr
          v-for="{ row, rowIndex } in visibleRows"
          :key="row.id"
          :data-row-index="rowIndex"
          :class="{
            'bg-neutral-500/5': (rowIndex + 1) % 2 === 0 && row.state === 'clean',
            'bg-emerald-500/8': row.state === 'new',
            'bg-amber-500/8': row.state === 'modified',
            'bg-red-500/10 line-through': row.state === 'deleted',
          }"
        >
          <td
            class="border app-border px-3 text-center sticky left-0 z-10 bg-neutral-50 dark:bg-neutral-900 mono text-xs border-l-0"
            :style="{
              width: `${rowHeaderColumnWidth}px`,
              minWidth: `${rowHeaderColumnWidth}px`,
              maxWidth: `${rowHeaderColumnWidth}px`,
            }"
            @click="selectRow(rowIndex)"
          >
            <div class="flex items-center gap-2 py-1">
              <span
                class="w-2 h-2 rounded-full"
                :class="{
                  'bg-transparent border border-neutral-300 dark:border-neutral-700':
                    row.state === 'clean',
                  'bg-emerald-500': row.state === 'new',
                  'bg-amber-500': row.state === 'modified',
                  'bg-red-500': row.state === 'deleted',
                }"
              />
              <span class="opacity-60">{{ rowIndex + 1 }}</span>
            </div>
          </td>

          <td
            v-for="(column, columnIndex) of columns"
            :key="column.field"
            :data-cell-row="rowIndex"
            :data-cell-column="columnIndex"
            class="border app-border mono text-xs align-top"
            :class="{
              'opacity-65': row.state === 'deleted',
            }"
            :style="{
              width: `${widths[column.field] || 220}px`,
              minWidth: `${widths[column.field] || 220}px`,
              maxWidth: `${widths[column.field] || 220}px`,
            }"
            @mousedown="onCellMouseDown($event, rowIndex, columnIndex)"
            @dblclick="startEditing(rowIndex, columnIndex)"
            @contextmenu.prevent="showContextMenu($event, rowIndex, columnIndex)"
          >
            <SQLTableCellEditor
              v-if="
                editingCell?.row === rowIndex &&
                editingCell?.column === columnIndex &&
                row.state !== 'deleted'
              "
              ref="editingEditor"
              v-model="editingValue"
              :column="column"
              @commit="commitEditing"
              @cancel="cancelEditing"
            />

            <div
              v-else
              class="px-1.5 py-1 min-h-[1.5rem] max-w-full overflow-hidden whitespace-nowrap truncate"
              :class="{
                'text-primary-500/80': row.state === 'new',
                'text-amber-500/90': row.state === 'modified',
              }"
            >
              <span v-if="getRowValue(row, column) === null || getRowValue(row, column) === undefined" class="opacity-35">
                NULL
              </span>
              <span
                v-else
                class="inline-flex max-w-full items-center gap-1 overflow-hidden truncate align-top"
              >
                <template v-for="(segment, segmentIndex) in getCachedDisplaySegments(row, column)" :key="segmentIndex">
                  <span
                    v-if="/^\r?\n$/.test(segment)"
                    class="inline-flex shrink-0 items-center rounded-sm bg-neutral-100 px-1 py-0.5 text-[11px] leading-none text-neutral-500 dark:bg-neutral-800 dark:text-neutral-400"
                  >
                    \n
                  </span>
                  <span v-else class="truncate">
                    {{ segment }}
                  </span>
                </template>
              </span>
              <i v-if="column.readOnly" class="ti ti-lock text-[11px] opacity-30" />
            </div>
          </td>
        </tr>

        <tr v-if="virtualPaddingBottom > 0" aria-hidden="true">
          <td
            :colspan="columns.length + 1"
            class="border-0 p-0"
            :style="{ height: `${virtualPaddingBottom}px` }"
          />
        </tr>
      </tbody>
    </table>
    </div>

    <ContextMenu
      ref="contextMenu"
      class="text-xs"
      :pt="{ itemLink: 'p-2 px-3' }"
      :model="contextMenuItems"
    />
  </div>
</template>
