import type { SQLTableColumn } from '@/types/sql'

export type EditorKind = 'text' | 'textarea' | 'enum' | 'date' | 'datetime' | 'time'

export const CELL_PREVIEW_TEXT_LIMIT = 150
export const DRAG_SCROLL_THRESHOLD = 48
export const DRAG_SCROLL_STEP = 20
export const VIRTUALIZATION_ROW_THRESHOLD = 200
export const VIRTUAL_ROW_HEIGHT = 30
export const VIRTUAL_OVERSCAN_ROWS = 12

const GENERATED_DEFAULT_VALUES = new Set([
  'current_timestamp',
  'current_timestamp()',
  'current_date',
  'current_date()',
  'current_time',
  'current_time()',
  'localtimestamp',
  'localtimestamp()',
  'now()',
  'uuid()',
  'gen_random_uuid()',
])

const pad = (value: number) => String(value).padStart(2, '0')

export const createRowId = () =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `row-${Date.now()}-${Math.random().toString(36).slice(2)}`

export const cloneCellValue = (value: unknown) => {
  if (value instanceof Date) {
    return new Date(value)
  }

  return value
}

export const isGeneratedDefaultValue = (value: unknown) => {
  if (typeof value !== 'string') {
    return false
  }

  return GENERATED_DEFAULT_VALUES.has(value.trim().toLowerCase())
}

export const isAutoGeneratedColumn = (column: SQLTableColumn) =>
  column.autoIncrement === true || isGeneratedDefaultValue(column.defaultValue)

export const buildColumnWidths = (
  nextColumns: SQLTableColumn[],
  previousWidths: Record<string, number>,
) =>
  nextColumns.reduce(
    (nextWidths, column) => ({
      ...nextWidths,
      [column.field]: previousWidths[column.field] ?? 220,
    }),
    {} as Record<string, number>,
  )

export const valuesEqual = (left: unknown, right: unknown) => {
  if (left === right) return true

  if (left instanceof Date && right instanceof Date) {
    return left.getTime() === right.getTime()
  }

  return false
}

export const formatDisplayValue = (value: unknown) => {
  const text =
    typeof value === 'string' ? value : value === null || value === undefined ? '' : String(value)

  if (text.length <= CELL_PREVIEW_TEXT_LIMIT) {
    return text
  }

  return `${text.slice(0, CELL_PREVIEW_TEXT_LIMIT)}...`
}

export const getDisplayText = (value: unknown) =>
  formatDisplayValue(typeof value === 'string' ? value.replace(/\r?\n/g, ' \\n ') : value)

export const getEditorKind = (column: SQLTableColumn): EditorKind => {
  const type = (column.type || '').toLowerCase()

  if (column.enumValues?.length) return 'enum'
  if (/\b(timestamp|datetime)\b/.test(type)) return 'datetime'
  if (/\btime\b/.test(type) && !/\b(timestamp|datetime)\b/.test(type)) return 'time'
  if (/\bdate\b/.test(type)) return 'date'

  return 'text'
}

const formatDateForColumn = (value: Date, kind: EditorKind) => {
  if (kind === 'date') {
    return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`
  }

  if (kind === 'time') {
    return `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
  }

  return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())} ${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
}

export const normalizeCellInputValue = ({
  rawValue,
  currentValue,
  column,
}: {
  rawValue: unknown
  currentValue: unknown
  column: SQLTableColumn
}) => {
  const type = (column.type || '').toLowerCase()
  const editorKind = getEditorKind(column)

  if (rawValue instanceof Date) {
    return formatDateForColumn(rawValue, editorKind)
  }

  if (rawValue === null || rawValue === undefined) {
    return column.nullable !== false ? null : currentValue
  }

  const normalized = String(rawValue).trim()

  if (normalized === '' && column.nullable !== false) {
    return null
  }

  if (typeof currentValue === 'number' || /(int|decimal|float|double)/.test(type)) {
    const numericValue = Number(rawValue)
    return Number.isNaN(numericValue) ? rawValue : numericValue
  }

  if (typeof currentValue === 'boolean' || /(bool|tinyint\(1\))/.test(type)) {
    return ['1', 'true', 'yes'].includes(normalized.toLowerCase())
  }

  return rawValue
}
