<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, useTemplateRef, watch } from 'vue'
import ContextMenu, { type ContextMenuMethods } from 'primevue/contextmenu'
import ResizeKnob from '@/components/ResizeKnob.vue'
import ExtendedDataTableCellDisplay from '@/components/table/ExtendedDataTableCellDisplay.vue'
import SQLTableCellEditor from '@/components/table/SQLTableCellEditor.vue'
import type { CellPosition } from '@/components/table/extended-data-table.types'
import {
  DRAG_SCROLL_STEP,
  DRAG_SCROLL_THRESHOLD,
  buildColumnWidths,
  cloneCellValue,
  createRowId,
  isAutoGeneratedColumn,
  normalizeCellInputValue,
  valuesEqual,
} from '@/components/table/extended-data-table-utils'
import { useExtendedDataTableViewport } from '@/components/table/useExtendedDataTableViewport'
import { useToast } from 'primevue/usetoast'
import type { SQLTableColumn, SQLTableRowDraft } from '@/types/sql'

const props = withDefaults(
  defineProps<{
    canEdit?: boolean
  }>(),
  {
    canEdit: true,
  },
)

const emit = defineEmits<{
  'update:focusedRowIndex': [value: number | null]
}>()

const columns = defineModel<SQLTableColumn[]>('columns', { required: true })
const rows = defineModel<SQLTableRowDraft[]>('rows', { required: true })

const toast = useToast()
const gridContainer = useTemplateRef<HTMLDivElement>('gridContainer')
const tableHead = useTemplateRef<HTMLTableSectionElement>('tableHead')
const cornerHeaderCell = useTemplateRef<HTMLTableCellElement>('cornerHeaderCell')
const editingEditor = useTemplateRef<InstanceType<typeof SQLTableCellEditor>>('editingEditor')
const contextMenu = useTemplateRef<ContextMenuMethods>('contextMenu')

const widths = ref<Record<string, number>>({})

const anchorCell = ref<CellPosition | null>(null)
const focusCell = ref<CellPosition | null>(null)
const editingCell = ref<CellPosition | null>(null)
const editingValue = ref<unknown>('')
const isDragging = ref(false)
const contextCell = ref<CellPosition | null>(null)
const dragPointer = ref<{ x: number; y: number } | null>(null)

let dragScrollFrame = 0

const clampCell = (cell: CellPosition): CellPosition => ({
  row: Math.min(Math.max(cell.row, 0), Math.max(rows.value.length - 1, 0)),
  column: Math.min(Math.max(cell.column, 0), Math.max(columns.value.length - 1, 0)),
})

const isEditableColumn = (columnIndex: number) => {
  const column = columns.value[columnIndex]
  return props.canEdit && !!column && column.readOnly !== true
}

const findFirstEditableColumnIndex = () =>
  columns.value.findIndex((column) => column.readOnly !== true)

watch(
  columns,
  (nextColumns) => {
    widths.value = buildColumnWidths(nextColumns, widths.value)
  },
  { immediate: true },
)

const hasRows = computed(() => rows.value.length > 0 && columns.value.length > 0)
const focusedRowIndex = computed(() => {
  if (focusCell.value === null) {
    return null
  }

  return focusCell.value.row < rows.value.length ? focusCell.value.row : null
})

const selectionRange = computed(() => {
  if (!anchorCell.value || !focusCell.value || !hasRows.value) return null

  return {
    startRow: Math.min(anchorCell.value.row, focusCell.value.row),
    endRow: Math.max(anchorCell.value.row, focusCell.value.row),
    startColumn: Math.min(anchorCell.value.column, focusCell.value.column),
    endColumn: Math.max(anchorCell.value.column, focusCell.value.column),
  }
})

const selectionIsSingleCell = computed(
  () =>
    !!selectionRange.value &&
    selectionRange.value.startRow === selectionRange.value.endRow &&
    selectionRange.value.startColumn === selectionRange.value.endColumn,
)

const { ensureCellVisible, getCellPositionFromPointer, measuredRowHeight, renderedRows, scheduleViewportSync, shouldVirtualizeRows, visibleRowRange } =
  useExtendedDataTableViewport({
    gridContainer,
    tableHead,
    cornerHeaderCell,
    rows,
    columns,
    widths,
    editingCell,
    clampCell,
    hasRows,
  })

const getSelectedRowIndexes = () => {
  const range = selectionRange.value
  if (!range) return []

  return Array.from(
    { length: range.endRow - range.startRow + 1 },
    (_, index) => range.startRow + index,
  )
}

const isEditingRow = (rowIndex: number) => editingCell.value?.row === rowIndex

const focusGrid = () => {
  gridContainer.value?.focus()
}

const restoreGridFocusAfterEdit = () => {
  nextTick(() => {
    requestAnimationFrame(() => {
      focusGrid()
    })
  })
}

const finishPendingEdit = (nextCell?: CellPosition) => {
  if (!editingCell.value) return

  if (
    nextCell &&
    editingCell.value.row === nextCell.row &&
    editingCell.value.column === nextCell.column
  ) {
    return
  }

  commitEditing()
}

const setSelection = (
  cell: CellPosition,
  options?: { extend?: boolean; ensureVisible?: boolean },
) => {
  if (!hasRows.value) return

  const nextCell = clampCell(cell)
  finishPendingEdit(nextCell)

  if (options?.extend && anchorCell.value) {
    focusCell.value = nextCell
  } else {
    anchorCell.value = nextCell
    focusCell.value = nextCell
  }

  focusGrid()

  if (options?.ensureVisible !== false) {
    ensureCellVisible(nextCell)
  }
}

const selectAll = () => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: 0, column: 0 }
  focusCell.value = { row: rows.value.length - 1, column: columns.value.length - 1 }
  editingCell.value = null
  focusGrid()
}

const selectRow = (index: number) => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: index, column: 0 }
  focusCell.value = { row: index, column: columns.value.length - 1 }
  editingCell.value = null
  focusGrid()
}

const selectColumn = (index: number) => {
  if (!hasRows.value) return

  finishPendingEdit()
  anchorCell.value = { row: 0, column: index }
  focusCell.value = { row: rows.value.length - 1, column: index }
  editingCell.value = null
  focusGrid()
}

const isCellSelected = (rowIndex: number, columnIndex: number) => {
  if (!selectionRange.value) return false

  return (
    rowIndex >= selectionRange.value.startRow &&
    rowIndex <= selectionRange.value.endRow &&
    columnIndex >= selectionRange.value.startColumn &&
    columnIndex <= selectionRange.value.endColumn
  )
}

const isColumnSelected = (columnIndex: number) =>
  !!selectionRange.value &&
  columnIndex >= selectionRange.value.startColumn &&
  columnIndex <= selectionRange.value.endColumn

const recomputeRowState = (rowIndex: number) => {
  const row = rows.value[rowIndex]

  if (!row || row.state === 'deleted') return
  if (!row.original) {
    row.state = 'new'
    return
  }

  const isDirty = columns.value.some(
    (column) => !valuesEqual(row.values[column.field], row.original?.[column.field]),
  )

  row.state = isDirty ? 'modified' : 'clean'
}

const getValue = (rowIndex: number, columnIndex: number) => {
  const row = rows.value[rowIndex]
  const column = columns.value[columnIndex]
  return row?.values?.[column.field]
}

const setValue = (rowIndex: number, columnIndex: number, value: unknown) => {
  const row = rows.value[rowIndex]
  if (!row || row.state === 'deleted') return

  const field = columns.value[columnIndex].field
  row.values = {
    ...row.values,
    [field]: value,
  }

  recomputeRowState(rowIndex)
}

const startEditing = (rowIndex: number, columnIndex: number) => {
  if (!isEditableColumn(columnIndex)) return
  if (rows.value[rowIndex]?.state === 'deleted') return

  setSelection({ row: rowIndex, column: columnIndex })
  editingCell.value = { row: rowIndex, column: columnIndex }
  editingValue.value = getValue(rowIndex, columnIndex) ?? null

  nextTick(() => {
    editingEditor.value?.focusEditor()
  })
}

const commitEditing = () => {
  if (!editingCell.value) return

  const { row, column } = editingCell.value
  setValue(
    row,
    column,
    normalizeCellInputValue({
      rawValue: editingValue.value,
      currentValue: getValue(row, column),
      column: columns.value[column],
    }),
  )
  editingCell.value = null
}

const cancelEditing = () => {
  editingCell.value = null
  restoreGridFocusAfterEdit()
}

const addRow = () => {
  const values = columns.value.reduce(
    (previous, column) => ({
      ...previous,
      [column.field]: column.defaultValue ?? null,
    }),
    {},
  )

  rows.value.push({
    id: createRowId(),
    values,
    original: null,
    state: 'new',
  })

  const rowIndex = rows.value.length - 1
  const editableColumnIndex = findFirstEditableColumnIndex()
  const targetColumn = editableColumnIndex >= 0 ? editableColumnIndex : 0
  setSelection({ row: rowIndex, column: targetColumn })
  if (editableColumnIndex >= 0) {
    startEditing(rowIndex, editableColumnIndex)
  }
}

const duplicateSelectedRows = () => {
  const selectedRowIndexes = getSelectedRowIndexes()
  if (!selectedRowIndexes.length) return
  finishPendingEdit()

  const insertionIndex = Math.max(...selectedRowIndexes) + 1
  const duplicates = selectedRowIndexes
    .map((rowIndex) => rows.value[rowIndex])
    .filter((row): row is SQLTableRowDraft => !!row && row.state !== 'deleted')
    .map((row) => ({
      id: createRowId(),
      values: columns.value.reduce(
        (previous, column) => ({
          ...previous,
          [column.field]: isAutoGeneratedColumn(column)
            ? null
            : cloneCellValue(row.values[column.field]),
        }),
        {} as Record<string, unknown>,
      ),
      original: null,
      state: 'new' as const,
    }))

  if (!duplicates.length) return

  rows.value.splice(insertionIndex, 0, ...duplicates)
  setSelection({
    row: insertionIndex,
    column: focusCell.value?.column ?? 0,
  })
}

const deleteSelectedRows = () => {
  const selectedRowIndexes = getSelectedRowIndexes()
  if (!selectedRowIndexes.length) return
  finishPendingEdit()

  const indexes = [...selectedRowIndexes].sort((left, right) => right - left)

  for (const index of indexes) {
    const row = rows.value[index]
    if (!row) continue

    if (!row.original) {
      rows.value.splice(index, 1)
      continue
    }

    row.state = row.state === 'deleted' ? 'clean' : 'deleted'
  }

  editingCell.value = null

  if (rows.value.length) {
    setSelection({
      row: Math.min(indexes[indexes.length - 1], rows.value.length - 1),
      column: focusCell.value?.column ?? 0,
    })
  } else {
    anchorCell.value = null
    focusCell.value = null
  }
}

const setSelectionToNull = () => {
  if (!props.canEdit || !selectionRange.value) return

  for (let row = selectionRange.value.startRow; row <= selectionRange.value.endRow; row += 1) {
    if (rows.value[row]?.state === 'deleted') continue

    for (
      let column = selectionRange.value.startColumn;
      column <= selectionRange.value.endColumn;
      column += 1
    ) {
      if (!isEditableColumn(column)) continue
      setValue(row, column, null)
    }
  }
}

const discardSelectedChanges = () => {
  const indexes = [...getSelectedRowIndexes()].sort((left, right) => right - left)

  for (const rowIndex of indexes) {
    const row = rows.value[rowIndex]
    if (!row || row.state === 'deleted') continue

    if (!row.original) {
      rows.value.splice(rowIndex, 1)
      continue
    }

    row.values = { ...row.original }
    row.state = 'clean'
  }
}

const formatCellValue = (value: unknown) => {
  if (value === null || value === undefined) return 'NULL'
  return String(value)
}

const copySelection = async () => {
  if (!selectionRange.value) return

  const lines = []

  for (let row = selectionRange.value.startRow; row <= selectionRange.value.endRow; row += 1) {
    const line = []

    for (
      let column = selectionRange.value.startColumn;
      column <= selectionRange.value.endColumn;
      column += 1
    ) {
      line.push(formatCellValue(getValue(row, column)))
    }

    lines.push(line.join('\t'))
  }

  try {
    await navigator.clipboard.writeText(lines.join('\n'))
    toast.add({
      severity: 'success',
      summary: 'Copied selection',
      detail: 'Selection copied as tab-separated text',
      life: 1500,
    })
  } catch {
    toast.add({
      severity: 'warn',
      summary: 'Clipboard unavailable',
      detail: 'The selection could not be copied automatically',
      life: 1800,
    })
  }
}

const moveSelection = (deltaRow: number, deltaColumn: number, extend: boolean) => {
  if (!hasRows.value) return

  const baseCell = (extend ? focusCell.value : anchorCell.value) ?? { row: 0, column: 0 }
  setSelection(
    {
      row: baseCell.row + deltaRow,
      column: baseCell.column + deltaColumn,
    },
    { extend, ensureVisible: true },
  )
}

const updateDragSelectionFromPointer = (clientX: number, clientY: number) => {
  if (!isDragging.value || !anchorCell.value || !gridContainer.value) {
    return
  }

  const nextCell = getCellPositionFromPointer(clientX, clientY)
  if (!nextCell) {
    return
  }

  focusCell.value = nextCell
}

const stopDragAutoScroll = () => {
  if (dragScrollFrame) {
    cancelAnimationFrame(dragScrollFrame)
    dragScrollFrame = 0
  }
}

const runDragAutoScroll = () => {
  if (!isDragging.value || !dragPointer.value || !gridContainer.value) {
    dragScrollFrame = 0
    return
  }

  const container = gridContainer.value
  const rect = container.getBoundingClientRect()
  let deltaX = 0
  let deltaY = 0

  if (dragPointer.value.x < rect.left + DRAG_SCROLL_THRESHOLD) {
    deltaX = -Math.ceil(
      ((rect.left + DRAG_SCROLL_THRESHOLD - dragPointer.value.x) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  } else if (dragPointer.value.x > rect.right - DRAG_SCROLL_THRESHOLD) {
    deltaX = Math.ceil(
      ((dragPointer.value.x - (rect.right - DRAG_SCROLL_THRESHOLD)) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  }

  if (dragPointer.value.y < rect.top + DRAG_SCROLL_THRESHOLD) {
    deltaY = -Math.ceil(
      ((rect.top + DRAG_SCROLL_THRESHOLD - dragPointer.value.y) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  } else if (dragPointer.value.y > rect.bottom - DRAG_SCROLL_THRESHOLD) {
    deltaY = Math.ceil(
      ((dragPointer.value.y - (rect.bottom - DRAG_SCROLL_THRESHOLD)) / DRAG_SCROLL_THRESHOLD) *
        DRAG_SCROLL_STEP,
    )
  }

  if (deltaX || deltaY) {
    container.scrollLeft += deltaX
    container.scrollTop += deltaY
    updateDragSelectionFromPointer(dragPointer.value.x, dragPointer.value.y)
  }

  dragScrollFrame = requestAnimationFrame(runDragAutoScroll)
}

const startDragAutoScroll = () => {
  if (dragScrollFrame) {
    return
  }

  dragScrollFrame = requestAnimationFrame(runDragAutoScroll)
}

const onGridKeyDown = (event: KeyboardEvent) => {
  if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)
    return

  if (!hasRows.value) return

  const extend = event.shiftKey
  const commandOrCtrl = event.metaKey || event.ctrlKey

  if (commandOrCtrl && event.code === 'KeyA') {
    selectAll()
    event.preventDefault()
    return
  }

  if (commandOrCtrl && event.code === 'KeyC') {
    void copySelection()
    event.preventDefault()
    return
  }

  if (props.canEdit && commandOrCtrl && event.code === 'KeyD') {
    duplicateSelectedRows()
    event.preventDefault()
    return
  }

  if (event.code === 'Enter' || event.code === 'F2') {
    const cell = focusCell.value ?? { row: 0, column: 0 }
    startEditing(cell.row, cell.column)
    event.preventDefault()
    return
  }

  if (props.canEdit && commandOrCtrl && (event.code === 'Delete' || event.code === 'Backspace')) {
    deleteSelectedRows()
    event.preventDefault()
    return
  }

  if (props.canEdit && event.code === 'Delete') {
    setSelectionToNull()
    event.preventDefault()
    return
  }

  if (event.code === 'Tab') {
    moveSelection(0, event.shiftKey ? -1 : 1, false)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowRight') {
    moveSelection(0, 1, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowLeft') {
    moveSelection(0, -1, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowDown') {
    moveSelection(1, 0, extend)
    event.preventDefault()
    return
  }

  if (event.code === 'ArrowUp') {
    moveSelection(-1, 0, extend)
    event.preventDefault()
  }
}

const onCellMouseDown = (event: MouseEvent, rowIndex: number, columnIndex: number) => {
  if (event.button !== 0) return

  event.preventDefault()
  isDragging.value = true
  dragPointer.value = { x: event.clientX, y: event.clientY }
  setSelection(
    { row: rowIndex, column: columnIndex },
    { extend: event.shiftKey, ensureVisible: true },
  )
  startDragAutoScroll()
}

const onCellMouseEnter = (_event: MouseEvent, rowIndex: number, columnIndex: number) => {
  if (!isDragging.value) return
  if (!anchorCell.value) return

  focusCell.value = clampCell({ row: rowIndex, column: columnIndex })
}

const onDocumentMouseMove = (event: MouseEvent) => {
  if (!isDragging.value) {
    return
  }

  dragPointer.value = { x: event.clientX, y: event.clientY }
  updateDragSelectionFromPointer(event.clientX, event.clientY)
  startDragAutoScroll()
}

const onDocumentMouseUp = () => {
  isDragging.value = false
  dragPointer.value = null
  stopDragAutoScroll()
}

const showContextMenu = (event: MouseEvent, rowIndex?: number, columnIndex?: number) => {
  finishPendingEdit(
    rowIndex !== undefined && columnIndex !== undefined
      ? { row: rowIndex, column: columnIndex }
      : undefined,
  )

  if (rowIndex !== undefined && columnIndex !== undefined) {
    contextCell.value = { row: rowIndex, column: columnIndex }
    if (!isCellSelected(rowIndex, columnIndex)) {
      setSelection({ row: rowIndex, column: columnIndex })
    }
  }

  contextMenu.value?.show(event)
}

const contextMenuItems = computed(() => [
  {
    label: 'Edit cell',
    icon: 'ti ti-edit',
    disabled:
      !selectionIsSingleCell.value ||
      !props.canEdit ||
      !focusCell.value ||
      !isEditableColumn(focusCell.value.column),
    command: () => {
      const cell = focusCell.value
      if (cell) startEditing(cell.row, cell.column)
    },
  },
  {
    label: 'Copy selection',
    icon: 'ti ti-copy',
    command: () => void copySelection(),
  },
  {
    label: 'Set NULL',
    icon: 'ti ti-eraser',
    disabled: !props.canEdit,
    command: setSelectionToNull,
  },
  { separator: true },
  {
    label: 'Insert row',
    icon: 'ti ti-row-insert-bottom',
    disabled: !props.canEdit,
    command: addRow,
  },
  {
    label: 'Duplicate row(s)',
    icon: 'ti ti-copy-plus',
    disabled: !props.canEdit,
    command: duplicateSelectedRows,
  },
  {
    label: 'Delete row(s)',
    icon: 'ti ti-trash',
    disabled: !props.canEdit,
    command: deleteSelectedRows,
  },
  {
    label: 'Discard row changes',
    icon: 'ti ti-restore',
    disabled: !props.canEdit,
    command: discardSelectedChanges,
  },
])

onMounted(() => {
  window.addEventListener('mousemove', onDocumentMouseMove)
  window.addEventListener('mouseup', onDocumentMouseUp)
})

onUnmounted(() => {
  stopDragAutoScroll()
  window.removeEventListener('mousemove', onDocumentMouseMove)
  window.removeEventListener('mouseup', onDocumentMouseUp)
})

watch(
  focusedRowIndex,
  (nextValue) => {
    emit('update:focusedRowIndex', nextValue)
  },
  { immediate: true },
)

defineExpose({
  addRow,
  duplicateSelectedRows,
  deleteSelectedRows,
  focusGrid,
  focusRow: (rowIndex: number, columnIndex = 0) => {
    if (!rows.value[rowIndex]) {
      return
    }

    setSelection({ row: rowIndex, column: columnIndex })
  },
  getFocusedRowIndex: () => focusedRowIndex.value,
  getSelectedRowIndexes: () => [...getSelectedRowIndexes()],
})
</script>

<template>
  <div
    ref="gridContainer"
    tabindex="0"
    class="h-full overflow-auto outline-none"
    @scroll.passive="scheduleViewportSync"
    @keydown="onGridKeyDown"
    @contextmenu.prevent="showContextMenu($event)"
  >
    <table class="m-[-1px] select-none" style="width: max-content">
      <thead ref="tableHead">
        <tr class="sticky top-0 left-0 bg-[#F9F9F9] dark:bg-[#202020] z-20">
          <th
            ref="cornerHeaderCell"
            class="sticky left-0 z-30 bg-[#F9F9F9] dark:bg-[#202020] border app-border border-t-0 border-l-0"
          >
            <button
              class="w-full h-full min-w-[3rem] hover:bg-neutral-500/10 text-xs uppercase tracking-[0.14em] rounded-md py-2 opacity-55"
              @click="selectAll"
            >
              All
            </button>
          </th>

          <th
            v-for="(column, columnIndex) of columns"
            :key="column.field"
            align="left"
            class="border app-border font-normal mono text-xs relative border-t-0 select-none"
            :class="{ 'bg-black/5 dark:bg-white/10': isColumnSelected(columnIndex) }"
            :style="{ width: `${widths[column.field] || 220}px` }"
            @click="selectColumn(columnIndex)"
          >
            <div class="flex items-center gap-2 justify-between px-2 py-1">
              <div class="flex items-center gap-2 min-w-0">
                <i
                  :class="`ti ${column.primaryKey ? 'ti-key text-amber-500' : 'ti-columns-3 opacity-50'}`"
                />
                <div class="flex flex-col min-w-0">
                  <span class="truncate">{{ column.name }}</span>
                  <span class="truncate text-[10px] opacity-45 mt-[-2px]">{{
                    column.type || 'column'
                  }}</span>
                </div>
              </div>
              <i class="ti ti-selector opacity-35" />
            </div>

            <ResizeKnob
              v-model:width="widths[column.field]"
              class="absolute right-[-0.3rem] top-0 z-10"
            />
          </th>
        </tr>
      </thead>

      <tbody>
        <tr v-if="visibleRowRange.topSpacerHeight > 0" aria-hidden="true">
          <td
            :colspan="columns.length + 1"
            class="border-0 p-0"
            :style="{ height: `${visibleRowRange.topSpacerHeight}px` }"
          />
        </tr>

        <tr
          v-for="{ row, rowIndex } in renderedRows"
          :key="row.id"
          data-virtual-row="true"
          :data-is-editing-row="isEditingRow(rowIndex) ? 'true' : 'false'"
          :class="{
            'bg-neutral-500/5': (rowIndex + 1) % 2 === 0 && row.state === 'clean',
            'bg-emerald-500/8': row.state === 'new',
            'bg-amber-500/8': row.state === 'modified',
            'bg-red-500/10 line-through': row.state === 'deleted',
          }"
          :style="
            shouldVirtualizeRows && !isEditingRow(rowIndex)
              ? { height: `${measuredRowHeight}px` }
              : undefined
          "
        >
          <td
            class="border app-border px-3 text-center sticky left-0 z-10 bg-neutral-50 dark:bg-neutral-900 mono text-xs border-l-0"
            @click="selectRow(rowIndex)"
          >
            <div class="flex items-center gap-2 py-1">
              <span
                class="w-2 h-2 rounded-full"
                :class="{
                  'bg-transparent border border-neutral-300 dark:border-neutral-700':
                    row.state === 'clean',
                  'bg-emerald-500': row.state === 'new',
                  'bg-amber-500': row.state === 'modified',
                  'bg-red-500': row.state === 'deleted',
                }"
              />
              <span class="opacity-60">{{ rowIndex + 1 }}</span>
            </div>
          </td>

          <td
            v-for="(column, columnIndex) of columns"
            :key="column.field"
            :data-cell-row="rowIndex"
            :data-cell-column="columnIndex"
            class="border app-border mono text-xs align-top"
            :class="{
              'bg-primary-500/18 ring-inset ring-1 ring-primary-500/30': isCellSelected(
                rowIndex,
                columnIndex,
              ),
              'opacity-65': row.state === 'deleted',
            }"
            :style="{
              width: `${widths[column.field] || 220}px`,
              minWidth: `${widths[column.field] || 220}px`,
              maxWidth: `${widths[column.field] || 220}px`,
            }"
            @mousedown="onCellMouseDown($event, rowIndex, columnIndex)"
            @mouseenter="onCellMouseEnter($event, rowIndex, columnIndex)"
            @dblclick="startEditing(rowIndex, columnIndex)"
            @contextmenu.prevent="showContextMenu($event, rowIndex, columnIndex)"
          >
            <SQLTableCellEditor
              v-if="
                editingCell?.row === rowIndex &&
                editingCell?.column === columnIndex &&
                row.state !== 'deleted'
              "
              ref="editingEditor"
              v-model="editingValue"
              :column="column"
              @commit="commitEditing"
              @cancel="cancelEditing"
            />

            <ExtendedDataTableCellDisplay
              v-else
              :value="getValue(rowIndex, columnIndex)"
              :row-state="row.state"
              :read-only="column.readOnly"
            />
          </td>
        </tr>

        <tr v-if="visibleRowRange.bottomSpacerHeight > 0" aria-hidden="true">
          <td
            :colspan="columns.length + 1"
            class="border-0 p-0"
            :style="{ height: `${visibleRowRange.bottomSpacerHeight}px` }"
          />
        </tr>
      </tbody>
    </table>

    <ContextMenu
      ref="contextMenu"
      class="text-xs"
      :pt="{ itemLink: 'p-2 px-3' }"
      :model="contextMenuItems"
    />
  </div>
</template>
