import type { SQLEditTableColumnDraft } from '@/types/sql'
import type {
  TableCheckDraft,
  TableColumnDraft,
  TableForeignKeyDraft,
  TableIndexDraft,
  TableKeyDraft,
  TableTriggerDraft,
  TableVirtualColumnDraft,
} from '@/types/table-schema'
import { quoteSqlIdentifier } from '@/datasources/shared-sql/dialect'
import { defineSqlTableSchemaDialect } from '@/datasources/shared-sql/schema/dialect-types'
import {
  columnList,
  normalizeDefaultValue,
  normalizeName,
  tableRef,
} from '@/datasources/shared-sql/schema/utils'

function unsupportedEdit(operation: string): never {
  throw new Error(`Oracle schema editing does not support ${operation} in this editor yet.`)
}

function emptySelect(columns: string[]) {
  return `SELECT ${columns.join(', ')} FROM dual WHERE 1 = 0`
}

function buildOracleColumnDefinition(column: TableColumnDraft | SQLEditTableColumnDraft) {
  if (!normalizeName(column.name)) {
    throw new Error('Columns require a name')
  }

  if (!column.type.trim()) {
    throw new Error(`Column ${column.name} requires a SQL type`)
  }

  const parts = [quoteSqlIdentifier(column.name, 'oracle'), column.type.trim()]
  if (column.autoIncrement) {
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  }

  parts.push(column.nullable ? 'NULL' : 'NOT NULL')

  const defaultValue = normalizeDefaultValue(column.defaultValue)
  if (defaultValue) {
    parts.push(`DEFAULT ${defaultValue}`)
  }

  return parts.join(' ')
}

function buildConstraintName(name: string) {
  const normalized = normalizeName(name)
  if (!normalized) {
    throw new Error('A valid constraint name is required')
  }

  return quoteSqlIdentifier(normalized, 'oracle')
}

export const oracleTableSchemaDialect = defineSqlTableSchemaDialect({
  type: 'oracle',
  buildMetadataQuery() {
    return [
      emptySelect([
        'CAST(NULL AS VARCHAR2(128)) AS name',
        'CAST(NULL AS VARCHAR2(32)) AS constraint_type',
        'CAST(NULL AS VARCHAR2(4000)) AS column_names',
      ]),
      emptySelect([
        'CAST(NULL AS VARCHAR2(128)) AS name',
        'CAST(NULL AS VARCHAR2(4000)) AS column_names',
        'CAST(NULL AS VARCHAR2(128)) AS referenced_table',
        'CAST(NULL AS VARCHAR2(4000)) AS referenced_column_names',
        'CAST(NULL AS VARCHAR2(32)) AS delete_rule',
        'CAST(NULL AS VARCHAR2(32)) AS update_rule',
      ]),
      emptySelect([
        'CAST(NULL AS VARCHAR2(128)) AS name',
        'CAST(0 AS NUMBER(1)) AS is_unique',
        'CAST(NULL AS VARCHAR2(32)) AS index_method',
        'CAST(NULL AS VARCHAR2(4000)) AS column_names',
      ]),
      emptySelect(['CAST(NULL AS VARCHAR2(128)) AS name', 'CAST(NULL AS VARCHAR2(4000)) AS expression']),
      emptySelect([
        'CAST(NULL AS VARCHAR2(128)) AS name',
        'CAST(NULL AS VARCHAR2(32)) AS timing',
        'CAST(NULL AS VARCHAR2(32)) AS event_name',
        'CAST(NULL AS VARCHAR2(4000)) AS action_statement',
      ]),
      emptySelect([
        'CAST(NULL AS VARCHAR2(128)) AS name',
        'CAST(NULL AS VARCHAR2(128)) AS column_type',
        'CAST(NULL AS VARCHAR2(1)) AS is_nullable',
        'CAST(NULL AS VARCHAR2(4000)) AS generation_expression',
      ]),
    ].join(';\n')
  },
  buildTriggerSql() {
    unsupportedEdit('creating triggers')
  },
  parseCheckExpression(row) {
    return String(row.definition ?? row.expression ?? '')
  },
  getVirtualColumnStorage() {
    return 'virtual'
  },
  buildColumnDefinition(column) {
    return buildOracleColumnDefinition(column)
  },
  buildVirtualColumnDefinition() {
    unsupportedEdit('virtual columns')
  },
  buildKeyDefinition(key: TableKeyDraft) {
    const kind = key.type === 'primary' ? 'PRIMARY KEY' : 'UNIQUE'
    return `CONSTRAINT ${buildConstraintName(key.name)} ${kind} (${columnList(key.columns, 'oracle')})`
  },
  buildForeignKeyDefinition(foreignKey: TableForeignKeyDraft) {
    if (!foreignKey.referencedTable.trim()) {
      throw new Error(`Foreign key ${foreignKey.name} requires a referenced table`)
    }

    const parts = [
      `CONSTRAINT ${buildConstraintName(foreignKey.name)}`,
      `FOREIGN KEY (${columnList(foreignKey.columns, 'oracle')})`,
      `REFERENCES ${quoteSqlIdentifier(foreignKey.referencedTable.trim(), 'oracle')} (${columnList(foreignKey.referencedColumns, 'oracle')})`,
    ]

    if (foreignKey.onDelete.trim()) {
      parts.push(`ON DELETE ${foreignKey.onDelete.trim()}`)
    }

    return parts.join(' ')
  },
  buildCheckDefinition(check: TableCheckDraft) {
    if (!check.expression.trim()) {
      throw new Error(`Check ${check.name} requires an expression`)
    }

    return `CONSTRAINT ${buildConstraintName(check.name)} CHECK (${check.expression.trim()})`
  },
  buildIndexStatement(tableName, index: TableIndexDraft) {
    const indexName = normalizeName(index.name)
    if (!indexName) {
      throw new Error('Indexes require a name')
    }

    return `CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${quoteSqlIdentifier(indexName, 'oracle')} ON ${tableRef(tableName, 'oracle')} (${columnList(index.columns, 'oracle')})`
  },
  buildDropKeyStatement() {
    unsupportedEdit('dropping keys')
  },
  buildDropForeignKeyStatement() {
    unsupportedEdit('dropping foreign keys')
  },
  buildDropCheckStatement() {
    unsupportedEdit('dropping checks')
  },
  buildDropIndexStatement() {
    unsupportedEdit('dropping indexes')
  },
  buildDropVirtualColumnStatement() {
    unsupportedEdit('dropping virtual columns')
  },
  buildDropTriggerStatement() {
    unsupportedEdit('dropping triggers')
  },
  buildAlterTableStatements({ tableName, originalColumns, nextColumns }) {
    const quotedTableName = tableRef(tableName, 'oracle')
    const originalByName = new Map(originalColumns.map((column) => [column.name, column]))
    const keptOriginalNames = new Set(
      nextColumns.map((column) => column.originalName).filter((value): value is string => Boolean(value)),
    )

    const statements: string[] = []

    for (const original of originalColumns) {
      if (!keptOriginalNames.has(original.name)) {
        statements.push(`ALTER TABLE ${quotedTableName} DROP COLUMN ${quoteSqlIdentifier(original.name, 'oracle')}`)
      }
    }

    for (const column of nextColumns) {
      if (!column.originalName) {
        statements.push(`ALTER TABLE ${quotedTableName} ADD (${buildOracleColumnDefinition(column)})`)
        continue
      }

      const original = originalByName.get(column.originalName)
      if (!original) {
        continue
      }

      const unchanged =
        original.name === column.name &&
        (original.type || '').trim() === column.type.trim() &&
        Boolean(original.nullable) === column.nullable &&
        normalizeDefaultValue(original.defaultValue) === normalizeDefaultValue(column.defaultValue)

      if (unchanged) {
        continue
      }

      const currentName = quoteSqlIdentifier(original.name, 'oracle')
      const nextName = quoteSqlIdentifier(column.name, 'oracle')
      const targetName = original.name !== column.name ? nextName : currentName

      if (original.name !== column.name) {
        statements.push(`ALTER TABLE ${quotedTableName} RENAME COLUMN ${currentName} TO ${nextName}`)
      }

      if ((original.type || '').trim() !== column.type.trim()) {
        statements.push(`ALTER TABLE ${quotedTableName} MODIFY (${targetName} ${column.type.trim()})`)
      }

      if (Boolean(original.nullable) !== column.nullable) {
        statements.push(`ALTER TABLE ${quotedTableName} MODIFY (${targetName} ${column.nullable ? 'NULL' : 'NOT NULL'})`)
      }

      if (normalizeDefaultValue(original.defaultValue) !== normalizeDefaultValue(column.defaultValue)) {
        const nextDefault = normalizeDefaultValue(column.defaultValue)
        statements.push(
          `ALTER TABLE ${quotedTableName} MODIFY (${targetName} ${nextDefault ? `DEFAULT ${nextDefault}` : 'DEFAULT NULL'})`,
        )
      }
    }

    return statements
  },
})
